namespace EarthInBeatsEngine.Graphics
{
	enum ModelType
	{
		Earth,
		Satellite,
		Spaceship
	};

	//interface IModel
	//{
	//	String GetModelPath();
	//	String GetModelName();
	//	ModelType GetModelType();
	//	IVector<String> GetTexturePaths();
	//};

	runtimeclass Renderer
	{
		Renderer();

		// TODO
		//void Initialize(
		//	Windows.UI.Xaml.Controls.SwapChainPanel panel,
		//	IVector<IModel> models, 
		//	IVector<String> bgTextures,
		//	Int32 width, Int32 height);

		Windows.Foundation.IAsyncAction Initialize(
			Windows.UI.Xaml.Controls.SwapChainPanel panel,
			UInt32 width, 
			UInt32 height,
			String modelPath,
			String backgroundTexturePath,
			String modelTextureOverridePath);

		void Resize(UInt32 width, UInt32 height);

		void Render();
		void Shutdown();

		//void LoadModels(IVector<IModel> models);
		//void LoadBackgrounds(IVector<String> textures);

		void SetRotation(Single yaw, Single pitch);
		void SetZoom(Single delta);

		Boolean Manipulation { get; set; };
	}
}